<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Acquisition Person' => 'Sammler',
  'Altitude' => 'Altitude',
  'Country Code' => 'Ländercode',
  'Exactness' => 'Genaugikeit',
  'Ipen Code' => 'IPEN Code',
  'Latitude' => 'Latitude',
  'Longitude' => 'Longitude',
  'Parent Organisation' => 'Übergeordnete Organisation',
  'Acquisition' => 'Aufsammlung',
  'Agent Id' => 'Sammler',
  'Certificates' => 'Zertifikate',
  'Create' => 'Erstellen',
  'Create Garden Site' => 'Standort erstellen',
  'Create Living Plant' => 'Lebendpflanze erstellen',
  'Create Tree Record File' => 'Baumkontrollblatt erstellen',
  'Garden Sites' => 'Standorte',
  'Living Plants' => 'Lebendpflanzen',
  'Login' => 'Login',
  'Logout' => 'Logout',
  'Manage' => 'Verwalten',
  'Manage Garden Site' => 'Standort verwalten',
  'Manage Garden Sites' => 'Standorte verwalten',
  'Manage Living Plant' => 'Lebenpflanze verwalten',
  'Manage Living Plants' => 'Lebendpflanzen verwalten',
  'Manage Tree Record File' => 'Baumkontrollblatt verwalten',
  'Manage Tree Record Files' => 'Baumkontrollblätter verwalten',
  'Parent Garden Site' => 'Übergeordneter Standort',
  'Phyto Sanitary Product Number' => 'Phytosanitärerzeugnisse Nr.',
  'Recording' => 'Aufnahme',
  'Separation' => 'Abgang',
  'Tree Record Files' => 'Baumkontrollblätter',
  'Update' => 'Aktualisieren',
  'Update Garden Site' => 'Standort aktualisieren',
  'Update Living Plant' => 'Lebendpflanze aktualisieren',
  'Update Tree Record File' => 'Baumkontrollblatt aktualisieren',
  'Accession Number' => 'Akzessionsnummer',
  'Acquisition Date' => 'Sammeldatum',
  'Acquisition Event' => 'Sammel Ereignis',
  'Acquisition Type' => 'Sammel Typ',
  'Annotation' => 'Bemerkung',
  'Botanical Object' => 'Botanisches Objekt',
  'Corrections Date' => 'Massnahmen Datum',
  'Corrections Done' => 'Massnahmen erledigt',
  'Custom' => 'Frei',
  'Date' => 'Datum',
  'Day' => 'Tag',
  'Department' => 'Abteilung',
  'Description' => 'Beschreibung',
  'Determined By' => 'Bestimmt durch',
  'Document Number' => 'Aktennummer',
  'Garden Site' => 'Standort',
  'Gardener' => 'Gärtner',
  'Geoname' => 'Geoname',
  'Greenhouse' => 'Gewächshaus',
  'Habitat' => 'Habitat',
  'Habitus' => 'Habitus',
  'ID' => 'ID',
  'Individual' => 'Individuum',
  'Ipen Number' => 'IPEN Nummer',
  'Living Plant' => 'Lebendpflanze',
  'Location' => 'Ort',
  'Month' => 'Monat',
  'Name' => 'Name',
  'Number' => 'Nummer',
  'Page' => 'Seite',
  'Password' => 'Passwort',
  'Phenology' => 'Phänologie',
  'Phyto Control' => 'Phyto-Kontrolle',
  'Place Number' => 'Platznummer',
  'Recording Date' => 'Aufnahmedatum',
  'Relevancy Type' => 'Relevanz',
  'Remember me next time' => 'Login merken',
  'Salt' => 'Salt',
  'Separation Type' => 'Abgang',
  'Service Data' => 'Service Daten',
  'Sex' => 'Geschlecht',
  'Taxon' => 'Taxon',
  'Tree Record File' => 'Baumkontrollblatt',
  'Tree Record File Page' => 'Baumkontrollblatt - Seite',
  'Type' => 'Typ',
  'Username' => 'Benutzername',
  'Year' => 'Jahr',
);
