<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'DNA sample' => 'DNA Proben',
  'cytological fixation' => 'Cytologische Fixierung',
  'dead (eliminated)' => 'Tot (eliminiert)',
  'dead (spontaneous)' => 'Tot (spontan)',
  'dead (unknown cause)' => 'Tot (unbekannte Ursache)',
  'doctoral_candidate' => 'Dissertant',
  'exhibition' => 'Ausstellung',
  'female' => 'weiblich',
  'fixed' => 'Stammpersonal',
  'florid' => 'Blüte',
  'foliage' => 'Laubaustrieb',
  'foliage_loss' => 'Laubfall',
  'fruit' => 'Frucht',
  'full extraction' => 'Vollständige Entnahme',
  'gardener' => 'Gartenpersonal',
  'harvested' => 'Abgebaut',
  'herb' => 'Kraut',
  'herbarium' => 'Herbar',
  'historic' => 'Historisch',
  'left_company' => 'Ausgeschieden',
  'male' => 'männlich',
  'morphological fixation' => 'Morphologische Fixierung',
  'partial extraction' => 'Teilweise Entnahme',
  'plant parts' => 'Pflanzenteile',
  'pollen' => 'Pollen',
  'postdoc' => 'Postdoc',
  'protection' => 'Naturschutz',
  'public' => 'Öffentlichkeit',
  'reduced' => 'Eingezogen',
  'sciences' => 'Forschung',
  'scientist' => 'Wissenschaftler',
  'seasonal' => 'Saisonkraft',
  'seed' => 'Samen',
  'separated' => 'Abgegeben',
  'shrub' => 'Strauch',
  'student' => 'Student',
  'teachings' => 'Lehre',
  'trainee' => 'Lehrling',
  'tree' => 'Baum',
  'unknown' => 'Unbekannt',
  'working' => 'Arbeit',
  'none' => 'Kein',
);
