-- MySQL Script generated by MySQL Workbench
-- 09/18/17 21:27:56
-- Model: Livingplants    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jacq_input
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jacq_input` ;

-- -----------------------------------------------------
-- Schema jacq_input
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jacq_input` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema jacq_log
-- -----------------------------------------------------
-- Note: this schema is auto-filled by the yii ActiveRecordLogableBehavior
-- -----------------------------------------------------
-- Schema herbarinput
-- -----------------------------------------------------
USE `jacq_input` ;

-- -----------------------------------------------------
-- Table `frmwrk_user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_user_type` ;

CREATE TABLE IF NOT EXISTS `frmwrk_user_type` (
  `user_type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frmwrk_employment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_employment_type` ;

CREATE TABLE IF NOT EXISTS `frmwrk_employment_type` (
  `employment_type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employment_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frmwrk_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_user` ;

CREATE TABLE IF NOT EXISTS `frmwrk_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  `password` VARCHAR(64) NOT NULL COMMENT 'SHA-256 hash',
  `salt` VARCHAR(64) NOT NULL COMMENT 'random salt',
  `user_type_id` INT NOT NULL,
  `employment_type_id` INT NOT NULL,
  `title_prefix` VARCHAR(45) NULL DEFAULT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `title_suffix` VARCHAR(45) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `organisation_id` INT NOT NULL,
  `force_password_change` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_frmwrk_user_frmwrk_user_type1_idx` (`user_type_id` ASC),
  INDEX `fk_frmwrk_user_frmwrk_employment_type1_idx` (`employment_type_id` ASC),
  INDEX `fk_frmwrk_user_tbl_organisation1_idx` (`organisation_id` ASC),
  CONSTRAINT `fk_frmwrk_user_frmwrk_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `frmwrk_user_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frmwrk_user_frmwrk_employment_type1`
    FOREIGN KEY (`employment_type_id`)
    REFERENCES `frmwrk_employment_type` (`employment_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frmwrk_user_tbl_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `tbl_organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_organisation` ;

CREATE TABLE IF NOT EXISTS `tbl_organisation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `department` VARCHAR(255) NULL,
  `greenhouse` TINYINT(1) NOT NULL DEFAULT 0,
  `parent_organisation_id` INT NULL DEFAULT NULL,
  `gardener_id` INT NULL,
  `ipen_code` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_garden_site_id_idx` (`parent_organisation_id` ASC),
  INDEX `fk_user_id_idx` (`gardener_id` ASC),
  CONSTRAINT `fk_garden_site_id`
    FOREIGN KEY (`parent_organisation_id`)
    REFERENCES `tbl_organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`gardener_id`)
    REFERENCES `frmwrk_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Table for maintaining garden-places';


-- -----------------------------------------------------
-- Table `tbl_acquisition_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_acquisition_date` ;

CREATE TABLE IF NOT EXISTS `tbl_acquisition_date` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(4) NULL,
  `month` VARCHAR(2) NULL,
  `day` VARCHAR(2) NULL,
  `custom` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Date table for entering even incomplete information';


-- -----------------------------------------------------
-- Table `tbl_acquisition_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_acquisition_type` ;

CREATE TABLE IF NOT EXISTS `tbl_acquisition_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_location` ;

CREATE TABLE IF NOT EXISTS `tbl_location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_location_coordinates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_location_coordinates` ;

CREATE TABLE IF NOT EXISTS `tbl_location_coordinates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `altitude_min` INT NULL,
  `altitude_max` INT NULL,
  `exactness` INT NULL,
  `latitude_degrees` INT NULL,
  `latitude_minutes` INT NULL,
  `latitude_seconds` INT NULL,
  `latitude_half` ENUM('N','S') NULL,
  `longitude_degrees` INT NULL,
  `longitude_minutes` INT NULL,
  `longitude_seconds` INT NULL,
  `longitude_half` ENUM('E','W') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_acquisition_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_acquisition_event` ;

CREATE TABLE IF NOT EXISTS `tbl_acquisition_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acquisition_date_id` INT NOT NULL,
  `acquisition_type_id` INT NOT NULL,
  `location_id` INT NULL DEFAULT NULL,
  `number` TEXT NULL,
  `annotation` TEXT NULL,
  `location_coordinates_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_acquisition_event_tbl_acquisition_date1_idx` (`acquisition_date_id` ASC),
  INDEX `fk_tbl_acquisition_event_tbl_acquisition_type1_idx` (`acquisition_type_id` ASC),
  INDEX `fk_tbl_acquisition_event_tbl_location1_idx` (`location_id` ASC),
  INDEX `fk_tbl_acquisition_event_tbl_location_coordinates_idx` (`location_coordinates_id` ASC),
  CONSTRAINT `fk_tbl_acquisition_event_tbl_acquisition_date`
    FOREIGN KEY (`acquisition_date_id`)
    REFERENCES `tbl_acquisition_date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_acquisition_event_tbl_acquisition_type`
    FOREIGN KEY (`acquisition_type_id`)
    REFERENCES `tbl_acquisition_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_acquisition_event_tbl_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `tbl_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_acquisition_event_tbl_location_coordinates`
    FOREIGN KEY (`location_coordinates_id`)
    REFERENCES `tbl_location_coordinates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_phenology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_phenology` ;

CREATE TABLE IF NOT EXISTS `tbl_phenology` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phenology` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phenology_UNIQUE` (`phenology` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_person` ;

CREATE TABLE IF NOT EXISTS `tbl_person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_ident_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_ident_status` ;

CREATE TABLE IF NOT EXISTS `tbl_ident_status` (
  `ident_status_id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ident_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_botanical_object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_botanical_object` ;

CREATE TABLE IF NOT EXISTS `tbl_botanical_object` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acquisition_event_id` INT NOT NULL,
  `phenology_id` INT NULL,
  `scientific_name_id` INT NOT NULL COMMENT 'Pointer to taxonID in old system',
  `determined_by_id` INT NULL,
  `determination_date` DATE NULL DEFAULT NULL,
  `habitat` VARCHAR(45) NULL,
  `habitus` VARCHAR(45) NULL,
  `annotation` TEXT NULL,
  `recording_date` DATETIME NOT NULL,
  `organisation_id` INT NULL DEFAULT 1,
  `accessible` TINYINT(1) NOT NULL DEFAULT 0,
  `redetermine` TINYINT(1) NOT NULL DEFAULT 0,
  `ident_status_id` INT NULL DEFAULT NULL,
  `separated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'indicates if the botanical object does not exist anymore',
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_object_tbl_acquisition_event1_idx` (`acquisition_event_id` ASC),
  INDEX `fk_tbl_object_tbl_phenology1_idx` (`phenology_id` ASC),
  INDEX `fk_tbl_botanical_object_tbl_person1_idx` (`determined_by_id` ASC),
  INDEX `fk_tbl_botanical_object_tbl_garden_site1_idx` (`organisation_id` ASC),
  INDEX `fk_tbl_botanical_object_tbl_ident_status1_idx` (`ident_status_id` ASC),
  CONSTRAINT `fk_tbl_object_tbl_acquisition_event1`
    FOREIGN KEY (`acquisition_event_id`)
    REFERENCES `tbl_acquisition_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_object_tbl_phenology1`
    FOREIGN KEY (`phenology_id`)
    REFERENCES `tbl_phenology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_botanical_object_tbl_person1`
    FOREIGN KEY (`determined_by_id`)
    REFERENCES `tbl_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_botanical_object_tbl_garden_site1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `tbl_organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_botanical_object_tbl_ident_status1`
    FOREIGN KEY (`ident_status_id`)
    REFERENCES `tbl_ident_status` (`ident_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_index_seminum_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_index_seminum_type` ;

CREATE TABLE IF NOT EXISTS `tbl_index_seminum_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_habitus_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_habitus_type` ;

CREATE TABLE IF NOT EXISTS `tbl_habitus_type` (
  `habitus_type_id` INT NOT NULL AUTO_INCREMENT,
  `habitus` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`habitus_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_scientific_name_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_scientific_name_information` ;

CREATE TABLE IF NOT EXISTS `tbl_scientific_name_information` (
  `scientific_name_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Pointer to taxonID in old system',
  `spatial_distribution` VARCHAR(255) NULL DEFAULT NULL,
  `common_names` VARCHAR(255) NULL DEFAULT NULL COMMENT 'text field for common names relevant to the garden',
  `habitus_type_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`scientific_name_id`),
  INDEX `fk_tbl_scientific_name_information_tbl_habitus_type1_idx` (`habitus_type_id` ASC),
  CONSTRAINT `fk_tbl_scientific_name_information_tbl_habitus_type1`
    FOREIGN KEY (`habitus_type_id`)
    REFERENCES `tbl_habitus_type` (`habitus_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_cultivar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_cultivar` ;

CREATE TABLE IF NOT EXISTS `tbl_cultivar` (
  `cultivar_id` INT NOT NULL AUTO_INCREMENT,
  `scientific_name_id` INT NOT NULL,
  `cultivar` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cultivar_id`),
  INDEX `fk_tbl_cultivar_tbl_scientific_name_information1_idx` (`scientific_name_id` ASC),
  CONSTRAINT `fk_tbl_cultivar_tbl_scientific_name_information1`
    FOREIGN KEY (`scientific_name_id`)
    REFERENCES `tbl_scientific_name_information` (`scientific_name_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_living_plant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_living_plant` ;

CREATE TABLE IF NOT EXISTS `tbl_living_plant` (
  `id` INT NOT NULL,
  `accession_number` INT NOT NULL AUTO_INCREMENT,
  `ipen_number` VARCHAR(20) NULL,
  `ipen_locked` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'No further editing possible',
  `ipen_type` ENUM('default', 'custom') NOT NULL DEFAULT 'default',
  `phyto_control` TINYINT(1) NOT NULL DEFAULT 0,
  `place_number` VARCHAR(20) NULL DEFAULT NULL,
  `index_seminum` TINYINT(1) NOT NULL DEFAULT 0,
  `culture_notes` TEXT NULL DEFAULT NULL,
  `cultivation_date` DATE NULL DEFAULT NULL,
  `index_seminum_type_id` INT NULL DEFAULT NULL,
  `incoming_date_id` INT NULL DEFAULT NULL,
  `label_synonym_scientific_name_id` INT NULL DEFAULT NULL COMMENT 'pointer to a taxonID for label printing (virtual synonym)',
  `cultivar_id` INT NULL DEFAULT NULL,
  `label_annotation` TEXT NULL DEFAULT NULL,
  `bgci` TINYINT(1) NOT NULL DEFAULT 0,
  `reviewed` TINYINT(1) NOT NULL DEFAULT 0,
  `has_image` TINYINT(1) NOT NULL DEFAULT 0,
  `has_public_image` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_living_plant_tbl_index_seminum_type1_idx` (`index_seminum_type_id` ASC),
  INDEX `fk_tbl_living_plant_tbl_acquisition_date1_idx` (`incoming_date_id` ASC),
  INDEX `fk_tbl_living_plant_tbl_cultivar1_idx` (`cultivar_id` ASC),
  UNIQUE INDEX `accession_number_UNIQUE` (`accession_number` ASC),
  INDEX `index_seminum_idx` (`index_seminum` ASC),
  CONSTRAINT `fk_livingplant_object1`
    FOREIGN KEY (`id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_living_plant_tbl_index_seminum_type1`
    FOREIGN KEY (`index_seminum_type_id`)
    REFERENCES `tbl_index_seminum_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_living_plant_tbl_acquisition_date1`
    FOREIGN KEY (`incoming_date_id`)
    REFERENCES `tbl_acquisition_date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_living_plant_tbl_cultivar1`
    FOREIGN KEY (`cultivar_id`)
    REFERENCES `tbl_cultivar` (`cultivar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_sex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_sex` ;

CREATE TABLE IF NOT EXISTS `tbl_sex` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sex` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sex_UNIQUE` (`sex` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_botanical_object_sex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_botanical_object_sex` ;

CREATE TABLE IF NOT EXISTS `tbl_botanical_object_sex` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sex_id` INT NOT NULL,
  `botanical_object_id` INT NOT NULL,
  INDEX `fk_table1_tbl_sex1_idx` (`sex_id` ASC),
  INDEX `fk_table1_tbl_object1_idx` (`botanical_object_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `object_id_sex_id_UNIQUE` (`sex_id` ASC, `botanical_object_id` ASC),
  CONSTRAINT `fk_table1_tbl_sex1`
    FOREIGN KEY (`sex_id`)
    REFERENCES `tbl_sex` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tbl_object1`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_diaspora_bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_diaspora_bank` ;

CREATE TABLE IF NOT EXISTS `tbl_diaspora_bank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_diaspora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_diaspora` ;

CREATE TABLE IF NOT EXISTS `tbl_diaspora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `diaspora_bank_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_diaspora_tbl_diaspora_bank1_idx` (`diaspora_bank_id` ASC),
  CONSTRAINT `fk_tbl_diaspora_tbl_object1`
    FOREIGN KEY (`id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_diaspora_tbl_diaspora_bank1`
    FOREIGN KEY (`diaspora_bank_id`)
    REFERENCES `tbl_diaspora_bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_separation_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_separation_type` ;

CREATE TABLE IF NOT EXISTS `tbl_separation_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_derivative_vegetative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_derivative_vegetative` ;

CREATE TABLE IF NOT EXISTS `tbl_derivative_vegetative` (
  `derivative_vegetative_id` INT NOT NULL AUTO_INCREMENT,
  `living_plant_id` INT NOT NULL,
  `accession_number` INT NOT NULL,
  `organisation_id` INT NOT NULL,
  `phenology_id` INT NOT NULL,
  `cultivation_date` DATE NULL DEFAULT NULL,
  `index_seminum` TINYINT(1) NOT NULL DEFAULT 0,
  `annotation` TEXT NULL DEFAULT NULL,
  `place_number` VARCHAR(20) NULL DEFAULT NULL,
  UNIQUE INDEX `accesion_number_livingplant_UNIQUE` (`accession_number` ASC, `living_plant_id` ASC),
  INDEX `fk_tbl_vegetative_derivative_tbl_organisation1_idx` (`organisation_id` ASC),
  INDEX `fk_tbl_vegetative_derivative_tbl_phenology1_idx` (`phenology_id` ASC),
  PRIMARY KEY (`derivative_vegetative_id`),
  INDEX `fk_tbl_derivative_vegetative_tbl_living_plant1_idx` (`living_plant_id` ASC),
  CONSTRAINT `fk_tbl_vegetative_derivative_tbl_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `tbl_organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_vegetative_derivative_tbl_phenology1`
    FOREIGN KEY (`phenology_id`)
    REFERENCES `tbl_phenology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_derivative_vegetative_tbl_living_plant1`
    FOREIGN KEY (`living_plant_id`)
    REFERENCES `tbl_living_plant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_separation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_separation` ;

CREATE TABLE IF NOT EXISTS `tbl_separation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `botanical_object_id` INT NULL DEFAULT NULL,
  `derivative_vegetative_id` INT NULL DEFAULT NULL,
  `separation_type_id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `annotation` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_separation_tbl_separation_type1_idx` (`separation_type_id` ASC),
  INDEX `fk_tbl_separation_tbl_botanical_object1_idx` (`botanical_object_id` ASC),
  INDEX `fk_tbl_separation_tbl_derivative_vegetative1_idx` (`derivative_vegetative_id` ASC),
  CONSTRAINT `fk_tbl_separation_tbl_separation_type1`
    FOREIGN KEY (`separation_type_id`)
    REFERENCES `tbl_separation_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_separation_tbl_botanical_object1`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_separation_tbl_derivative_vegetative1`
    FOREIGN KEY (`derivative_vegetative_id`)
    REFERENCES `tbl_derivative_vegetative` (`derivative_vegetative_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_relevancy_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_relevancy_type` ;

CREATE TABLE IF NOT EXISTS `tbl_relevancy_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(25) NULL,
  `important` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_relevancy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_relevancy` ;

CREATE TABLE IF NOT EXISTS `tbl_relevancy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `relevancy_type_id` INT NOT NULL,
  `living_plant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_relevancy_has_tbl_livingplant_tbl_livingplant1_idx` (`living_plant_id` ASC),
  INDEX `fk_tbl_relevancy_has_tbl_livingplant_tbl_relevancy1_idx` (`relevancy_type_id` ASC),
  UNIQUE INDEX `livingplant_relevancy_type_id_UNIQUE` (`relevancy_type_id` ASC, `living_plant_id` ASC),
  CONSTRAINT `fk_tbl_relevancy_has_tbl_livingplant_tbl_relevancy1`
    FOREIGN KEY (`relevancy_type_id`)
    REFERENCES `tbl_relevancy_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_relevancy_has_tbl_livingplant_tbl_livingplant1`
    FOREIGN KEY (`living_plant_id`)
    REFERENCES `tbl_living_plant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_specimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_specimen` ;

CREATE TABLE IF NOT EXISTS `tbl_specimen` (
  `specimen_id` INT(11) NOT NULL AUTO_INCREMENT,
  `botanical_object_id` INT(11) NOT NULL,
  `herbar_number` VARCHAR(20) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`specimen_id`),
  INDEX `fk_tbl_specimen_tbl_botanical_object1_idx` (`botanical_object_id` ASC),
  CONSTRAINT `fk_tbl_specimen_tbl_botanical_object1`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbl_tree_record_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_tree_record_file` ;

CREATE TABLE IF NOT EXISTS `tbl_tree_record_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` YEAR NULL,
  `name` VARCHAR(255) NULL,
  `document_number` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_tree_record_file_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_tree_record_file_page` ;

CREATE TABLE IF NOT EXISTS `tbl_tree_record_file_page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tree_record_file_id` INT NOT NULL,
  `page` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_tree_record_file_page_tbl_tree_record_file1_idx` (`tree_record_file_id` ASC),
  CONSTRAINT `fk_tbl_tree_record_file_page_tbl_tree_record_file1`
    FOREIGN KEY (`tree_record_file_id`)
    REFERENCES `tbl_tree_record_file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_living_plant_tree_record_file_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_living_plant_tree_record_file_page` ;

CREATE TABLE IF NOT EXISTS `tbl_living_plant_tree_record_file_page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `living_plant_id` INT NOT NULL,
  `tree_record_file_page_id` INT NOT NULL,
  `corrections_done` TINYINT(1) NOT NULL DEFAULT 0,
  `corrections_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_tree_record_tbl_tree_record_file_page1_idx` (`tree_record_file_page_id` ASC),
  INDEX `fk_tbl_living_plant_tree_record_tbl_living_plant1_idx` (`living_plant_id` ASC),
  CONSTRAINT `fk_tbl_tree_record_tbl_tree_record_file_page1`
    FOREIGN KEY (`tree_record_file_page_id`)
    REFERENCES `tbl_tree_record_file_page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_living_plant_tree_record_tbl_living_plant1`
    FOREIGN KEY (`living_plant_id`)
    REFERENCES `tbl_living_plant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_sequence` ;

CREATE TABLE IF NOT EXISTS `tbl_sequence` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_alternative_accession_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_alternative_accession_number` ;

CREATE TABLE IF NOT EXISTS `tbl_alternative_accession_number` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `living_plant_id` INT NOT NULL,
  `number` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_alternative_accession_number_tbl_living_plant1_idx` (`living_plant_id` ASC),
  CONSTRAINT `fk_tbl_alternative_accession_number_tbl_living_plant1`
    FOREIGN KEY (`living_plant_id`)
    REFERENCES `tbl_living_plant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'counter for ipen number';


-- -----------------------------------------------------
-- Table `tbl_location_geonames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_location_geonames` ;

CREATE TABLE IF NOT EXISTS `tbl_location_geonames` (
  `id` INT NOT NULL,
  `service_data` TEXT NOT NULL,
  `geonameId` INT NOT NULL,
  `countryCode` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `geonameId_UNIQUE` (`geonameId` ASC),
  CONSTRAINT `fk_tbl_geonames_location_tbl_location1`
    FOREIGN KEY (`id`)
    REFERENCES `tbl_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_acquisition_event_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_acquisition_event_person` ;

CREATE TABLE IF NOT EXISTS `tbl_acquisition_event_person` (
  `acquisition_event_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`acquisition_event_id`, `person_id`),
  INDEX `fk_tbl_acquisition_event_person_tbl_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_tbl_acquisition_event_person_tbl_acquisition_event1`
    FOREIGN KEY (`acquisition_event_id`)
    REFERENCES `tbl_acquisition_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_acquisition_event_person_tbl_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `tbl_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_certificate_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_certificate_type` ;

CREATE TABLE IF NOT EXISTS `tbl_certificate_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_certificate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_certificate` ;

CREATE TABLE IF NOT EXISTS `tbl_certificate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `living_plant_id` INT NOT NULL,
  `certificate_type_id` INT NOT NULL,
  `number` TEXT NULL,
  `annotation` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_certificate_tbl_certificate_type1_idx` (`certificate_type_id` ASC),
  INDEX `fk_tbl_certificate_tbl_living_plant1_idx` (`living_plant_id` ASC),
  CONSTRAINT `fk_tbl_certificate_tbl_certificate_type1`
    FOREIGN KEY (`certificate_type_id`)
    REFERENCES `tbl_certificate_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_certificate_tbl_living_plant1`
    FOREIGN KEY (`living_plant_id`)
    REFERENCES `tbl_living_plant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frmwrk_AuthItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_AuthItem` ;

CREATE TABLE IF NOT EXISTS `frmwrk_AuthItem` (
  `name` VARCHAR(64) NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frmwrk_AuthAssignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_AuthAssignment` ;

CREATE TABLE IF NOT EXISTS `frmwrk_AuthAssignment` (
  `itemname` VARCHAR(64) NOT NULL,
  `userid` INT NOT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`itemname`, `userid`),
  INDEX `fk_frmwrk_AuthAssignment_frmwrk_user1_idx` (`userid` ASC),
  INDEX `itemname` (`itemname` ASC),
  CONSTRAINT `fk_frmwrk_AuthAssignment_frmwrk_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `frmwrk_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `frmwrk_AuthAssignment_ibfk_1`
    FOREIGN KEY (`itemname`)
    REFERENCES `frmwrk_AuthItem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frmwrk_AuthItemChild`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_AuthItemChild` ;

CREATE TABLE IF NOT EXISTS `frmwrk_AuthItemChild` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `frmwrk_AuthItemChild_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `frmwrk_AuthItem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `frmwrk_AuthItemChild_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `frmwrk_AuthItem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frmwrk_accessOrganisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_accessOrganisation` ;

CREATE TABLE IF NOT EXISTS `frmwrk_accessOrganisation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `AuthItem_name` VARCHAR(64) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `allowDeny` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 = deny, 1 = allow',
  `organisation_id` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_frmwrk_AccessOrganisation_frmwrk_AuthItem1_idx` (`AuthItem_name` ASC),
  INDEX `fk_frmwrk_AccessOrganisation_frmwrk_user1_idx` (`user_id` ASC),
  INDEX `fk_frmwrk_accessOrganisation_tbl_organisation_idx` (`organisation_id` ASC),
  UNIQUE INDEX `user_assignment_UNIQUE` (`organisation_id` ASC, `user_id` ASC),
  INDEX `group_assignment_UNIQUE` (`organisation_id` ASC, `AuthItem_name` ASC),
  CONSTRAINT `fk_frmwrk_AccessOrganisation_frmwrk_AuthItem1`
    FOREIGN KEY (`AuthItem_name`)
    REFERENCES `frmwrk_AuthItem` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frmwrk_AccessOrganisation_frmwrk_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `frmwrk_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frmwrk_accessOrganisation_tbl_organisation`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `tbl_organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'access assignment for organisation level';


-- -----------------------------------------------------
-- Table `frmwrk_accessBotanicalObject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_accessBotanicalObject` ;

CREATE TABLE IF NOT EXISTS `frmwrk_accessBotanicalObject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `AuthItem_name` VARCHAR(64) NULL,
  `user_id` INT NULL,
  `allowDeny` TINYINT(1) NOT NULL DEFAULT 0,
  `botanical_object_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_frmwrk_accessLivingplant_frmwrk_AuthItem1_idx` (`AuthItem_name` ASC),
  INDEX `fk_frmwrk_accessLivingplant_frmwrk_user1_idx` (`user_id` ASC),
  INDEX `fk_frmwrk_accessLivingplant_tbl_living_plant_idx` (`botanical_object_id` ASC),
  UNIQUE INDEX `user_assignment_UNIQUE` (`user_id` ASC, `botanical_object_id` ASC),
  UNIQUE INDEX `group_assignment_UNIQUE` (`botanical_object_id` ASC, `AuthItem_name` ASC),
  CONSTRAINT `fk_frmwrk_accessLivingplant_frmwrk_AuthItem1`
    FOREIGN KEY (`AuthItem_name`)
    REFERENCES `frmwrk_AuthItem` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frmwrk_accessLivingplant_frmwrk_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `frmwrk_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frmwrk_accessLivingplant_tbl_living_plant`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_living_plant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_import_properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_import_properties` ;

CREATE TABLE IF NOT EXISTS `tbl_import_properties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `botanical_object_id` INT NOT NULL,
  `IDPflanze` INT NULL,
  `species_name` VARCHAR(255) NULL,
  `Verbreitung` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_import_properties_tbl_botanical_object1_idx` (`botanical_object_id` ASC),
  CONSTRAINT `fk_tbl_import_properties_tbl_botanical_object1`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_import_error`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_import_error` ;

CREATE TABLE IF NOT EXISTS `tbl_import_error` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IDPflanze` INT NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_acquisition_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_acquisition_source` ;

CREATE TABLE IF NOT EXISTS `tbl_acquisition_source` (
  `acquisition_source_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`acquisition_source_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_acquisition_event_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_acquisition_event_source` ;

CREATE TABLE IF NOT EXISTS `tbl_acquisition_event_source` (
  `acquisition_event_source_id` INT NOT NULL AUTO_INCREMENT,
  `acquisition_event_id` INT NOT NULL,
  `acquisition_source_id` INT NOT NULL,
  `source_date` DATE NULL DEFAULT NULL,
  INDEX `fk_tbl_acquisition_event_source_tbl_acquisition_event1_idx` (`acquisition_event_id` ASC),
  INDEX `fk_tbl_acquisition_event_source_tbl_acquisition_source1_idx` (`acquisition_source_id` ASC),
  PRIMARY KEY (`acquisition_event_source_id`),
  CONSTRAINT `fk_tbl_acquisition_event_source_tbl_acquisition_event1`
    FOREIGN KEY (`acquisition_event_id`)
    REFERENCES `tbl_acquisition_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_acquisition_event_source_tbl_acquisition_source1`
    FOREIGN KEY (`acquisition_source_id`)
    REFERENCES `tbl_acquisition_source` (`acquisition_source_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_label_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_label_type` ;

CREATE TABLE IF NOT EXISTS `tbl_label_type` (
  `label_type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`label_type_id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_botanical_object_label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_botanical_object_label` ;

CREATE TABLE IF NOT EXISTS `tbl_botanical_object_label` (
  `botanical_object_id` INT NOT NULL,
  `label_type_id` INT NOT NULL,
  INDEX `fk_tbl_botanical_object_label_tbl_botanical_object1_idx` (`botanical_object_id` ASC),
  INDEX `fk_tbl_botanical_object_label_tbl_label_type1_idx` (`label_type_id` ASC),
  PRIMARY KEY (`botanical_object_id`, `label_type_id`),
  CONSTRAINT `fk_tbl_botanical_object_label_tbl_botanical_object1`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_botanical_object_label_tbl_label_type1`
    FOREIGN KEY (`label_type_id`)
    REFERENCES `tbl_label_type` (`label_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_image_server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_image_server` ;

CREATE TABLE IF NOT EXISTS `tbl_image_server` (
  `organisation_id` INT NOT NULL,
  `base_url` TEXT NOT NULL,
  `key` VARCHAR(50) NOT NULL,
  `last_synchronized` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`organisation_id`),
  CONSTRAINT `fk_tbl_image_server_tbl_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `tbl_organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frmwrk_accessClassification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_accessClassification` ;

CREATE TABLE IF NOT EXISTS `frmwrk_accessClassification` (
  `access_classification_id` INT NOT NULL AUTO_INCREMENT,
  `AuthItem_name` VARCHAR(64) NULL,
  `user_id` INT NULL,
  `allowDeny` TINYINT(1) NOT NULL DEFAULT 0,
  `tax_syn_ID` INT NOT NULL DEFAULT 0 COMMENT 'reference to synonymy / classification table in legacy system',
  PRIMARY KEY (`access_classification_id`),
  INDEX `fk_frmwrk_accessClassification_frmwrk_AuthItem1_idx` (`AuthItem_name` ASC),
  INDEX `fk_frmwrk_accessClassification_frmwrk_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_frmwrk_accessClassification_frmwrk_AuthItem1`
    FOREIGN KEY (`AuthItem_name`)
    REFERENCES `frmwrk_AuthItem` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frmwrk_accessClassification_frmwrk_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `frmwrk_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srvc_uuid_minter_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srvc_uuid_minter_type` ;

CREATE TABLE IF NOT EXISTS `srvc_uuid_minter_type` (
  `uuid_minter_type_id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid_minter_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srvc_uuid_minter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srvc_uuid_minter` ;

CREATE TABLE IF NOT EXISTS `srvc_uuid_minter` (
  `uuid_minter_id` INT NOT NULL AUTO_INCREMENT,
  `uuid_minter_type_id` INT NOT NULL,
  `internal_id` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid_minter_id`),
  INDEX `fk_srvc_uuid_minter_srvc_uuid_minter_type1_idx` (`uuid_minter_type_id` ASC),
  CONSTRAINT `fk_srvc_uuid_minter_srvc_uuid_minter_type1`
    FOREIGN KEY (`uuid_minter_type_id`)
    REFERENCES `srvc_uuid_minter_type` (`uuid_minter_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_index_seminum_revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_index_seminum_revision` ;

CREATE TABLE IF NOT EXISTS `tbl_index_seminum_revision` (
  `index_seminum_revision_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`index_seminum_revision_id`),
  INDEX `fk_tbl_index_seminum_revision_frmwrk_user_idx` (`user_id` ASC),
  UNIQUE INDEX `revision_name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_tbl_index_seminum_revision_frmwrk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `frmwrk_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_index_seminum_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_index_seminum_content` ;

CREATE TABLE IF NOT EXISTS `tbl_index_seminum_content` (
  `index_seminum_content_id` INT NOT NULL AUTO_INCREMENT,
  `index_seminum_revision_id` INT NOT NULL,
  `botanical_object_id` INT NOT NULL,
  `accession_number` TEXT NOT NULL,
  `family` TEXT NOT NULL,
  `scientific_name` TEXT NOT NULL,
  `index_seminum_type` VARCHAR(3) NOT NULL,
  `ipen_number` VARCHAR(28) NOT NULL,
  `acquisition_number` TEXT NULL,
  `acquisition_location` TEXT NULL,
  `habitat` VARCHAR(45) NULL,
  `altitude_min` INT NULL,
  `altitude_max` INT NULL,
  `latitude` VARCHAR(14) NULL,
  `longitude` VARCHAR(14) NULL,
  `acquisition_date` VARCHAR(20) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`index_seminum_content_id`),
  INDEX `fk_tbl_index_seminum_content_tbl_botanical_object1_idx` (`botanical_object_id` ASC),
  INDEX `fk_tbl_index_seminum_content_tbl_index_seminum_revision1_idx` (`index_seminum_revision_id` ASC),
  CONSTRAINT `fk_tbl_index_seminum_content_tbl_botanical_object1`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_index_seminum_content_tbl_index_seminum_revision1`
    FOREIGN KEY (`index_seminum_revision_id`)
    REFERENCES `tbl_index_seminum_revision` (`index_seminum_revision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_index_seminum_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_index_seminum_person` ;

CREATE TABLE IF NOT EXISTS `tbl_index_seminum_person` (
  `index_seminum_person_id` INT NOT NULL AUTO_INCREMENT,
  `index_seminum_content_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`index_seminum_person_id`),
  INDEX `fk_tbl_index_seminum_person_tbl_index_seminum_content_idx` (`index_seminum_content_id` ASC),
  CONSTRAINT `fk_tbl_index_seminum_person_tbl_index_seminum_content`
    FOREIGN KEY (`index_seminum_content_id`)
    REFERENCES `tbl_index_seminum_content` (`index_seminum_content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_inventory_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_inventory_type` ;

CREATE TABLE IF NOT EXISTS `tbl_inventory_type` (
  `inventory_type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`inventory_type_id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_inventory` ;

CREATE TABLE IF NOT EXISTS `tbl_inventory` (
  `inventory_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `inventory_type_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`inventory_id`),
  INDEX `fk_tbl_inventory_tbl_inventory_type1_idx` (`inventory_type_id` ASC),
  INDEX `fk_tbl_inventory_frmwrk_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_inventory_tbl_inventory_type1`
    FOREIGN KEY (`inventory_type_id`)
    REFERENCES `tbl_inventory_type` (`inventory_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_inventory_frmwrk_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `frmwrk_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_inventory_object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_inventory_object` ;

CREATE TABLE IF NOT EXISTS `tbl_inventory_object` (
  `inventory_object_id` INT NOT NULL AUTO_INCREMENT,
  `inventory_id` INT NOT NULL,
  `botanical_object_id` INT NULL,
  `message` TEXT NOT NULL COMMENT 'Logging message produced by inventory type handler',
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`inventory_object_id`),
  INDEX `fk_tbl_inventory_object_tbl_inventory1_idx` (`inventory_id` ASC),
  INDEX `fk_tbl_inventory_object_tbl_botanical_object1_idx` (`botanical_object_id` ASC),
  CONSTRAINT `fk_tbl_inventory_object_tbl_inventory1`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `tbl_inventory` (`inventory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_inventory_object_tbl_botanical_object1`
    FOREIGN KEY (`botanical_object_id`)
    REFERENCES `tbl_botanical_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frmwrk_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_config` ;

CREATE TABLE IF NOT EXISTS `frmwrk_config` (
  `fc_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fc_name` VARCHAR(45) NOT NULL,
  `fc_value` TEXT NULL,
  PRIMARY KEY (`fc_id`),
  UNIQUE INDEX `fc_name_UNIQUE` (`fc_name` ASC))
ENGINE = InnoDB
COMMENT = 'Global config table for holding all configuration values of ' /* comment truncated */ /*the JACQ system.*/;


-- -----------------------------------------------------
-- Table `frmwrk_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frmwrk_template` ;

CREATE TABLE IF NOT EXISTS `frmwrk_template` (
  `ft_id` INT NOT NULL,
  `ft_name` VARCHAR(45) NOT NULL,
  `ft_template` BLOB NOT NULL,
  PRIMARY KEY (`ft_id`),
  UNIQUE INDEX `ft_name_UNIQUE` (`ft_name` ASC))
ENGINE = InnoDB
COMMENT = 'Generic template table for holding binary template files for' /* comment truncated */ /* processing (e.g. BIRT report layouts).*/;


-- -----------------------------------------------------
-- Table `rev_classification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rev_classification` ;

CREATE TABLE IF NOT EXISTS `rev_classification` (
  `classification_browser_revision_id` INT(11) NOT NULL AUTO_INCREMENT,
  `uuid_minter_id` INT NOT NULL,
  `classification_id` INT(11) NOT NULL DEFAULT '0',
  `scientific_name_id` INT(11) NOT NULL DEFAULT '0',
  `acc_scientific_name_id` INT(11) NULL DEFAULT NULL,
  `ref_date` DATE NULL DEFAULT NULL,
  `preferred_taxonomy` TINYINT(4) NOT NULL DEFAULT '0',
  `annotations` LONGTEXT NULL DEFAULT NULL,
  `locked` TINYINT(4) NOT NULL DEFAULT '0',
  `source` VARCHAR(20) NOT NULL DEFAULT '',
  `source_id` BIGINT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `parent_scientific_name_id` INT(11) NULL DEFAULT NULL,
  `number` VARCHAR(15) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `scientific_name` TEXT NULL DEFAULT NULL,
  `scientific_name_no_author` TEXT NULL DEFAULT NULL,
  `province_ids` TEXT NULL DEFAULT NULL,
  `province_codes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`classification_browser_revision_id`),
  INDEX `fk_tbl_classification_browser_revision_srvc_uuid_minter1_idx` (`uuid_minter_id` ASC),
  INDEX `uuid_minter_id` (`uuid_minter_id` ASC, `acc_scientific_name_id` ASC),
  CONSTRAINT `fk_tbl_classification_browser_revision_srvc_uuid_minter1`
    FOREIGN KEY (`uuid_minter_id`)
    REFERENCES `srvc_uuid_minter` (`uuid_minter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `jacq_input` ;

-- -----------------------------------------------------
-- Placeholder table for view `view_taxon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view_taxon` (`taxonID` INT, `synID` INT, `basID` INT, `genID` INT, `annotation` INT, `external` INT, `genus` INT, `DallaTorreIDs` INT, `DallaTorreZusatzIDs` INT, `author_g` INT, `family` INT, `category` INT, `status` INT, `statusID` INT, `rank` INT, `tax_rankID` INT, `rank_abbr` INT, `author` INT, `authorID` INT, `Brummit_Powell_full` INT, `author1` INT, `authorID1` INT, `bpf1` INT, `author2` INT, `authorID2` INT, `bpf2` INT, `author3` INT, `authorID3` INT, `bpf3` INT, `author4` INT, `authorID4` INT, `bpf4` INT, `author5` INT, `authorID5` INT, `bpf5` INT, `epithet` INT, `epithetID` INT, `epithet1` INT, `epithetID1` INT, `epithet2` INT, `epithetID2` INT, `epithet3` INT, `epithetID3` INT, `epithet4` INT, `epithetID4` INT, `epithet5` INT, `epithetID5` INT);

-- -----------------------------------------------------
-- Placeholder table for view `view_derivative_vegetative_count`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view_derivative_vegetative_count` (`living_plant_id` INT, `vegetative_count` INT);

-- -----------------------------------------------------
-- Placeholder table for view `view_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view_person` (`id` INT, `name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `view_scientificName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view_scientificName` (`scientific_name_id` INT, `scientific_name` INT, `scientific_name_no_author` INT);

-- -----------------------------------------------------
-- Placeholder table for view `tbl_classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_classification` (`classification_id` INT, `scientific_name_id` INT, `acc_scientific_name_id` INT, `ref_date` INT, `preferred_taxonomy` INT, `annotations` INT, `locked` INT, `source` INT, `source_id` INT, `user_id` INT, `timestamp` INT, `parent_scientific_name_id` INT, `number` INT, `order` INT);

-- -----------------------------------------------------
-- Placeholder table for view `tbl_classification_chorol_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_classification_chorol_status` (`classification_chorol_status_id` INT, `scientific_name_id` INT, `source` INT, `source_id` INT, `chorol_status` INT, `status_debatable` INT, `nation_id` INT, `province_id` INT, `province_debatable` INT, `date_last_edited` INT, `locked` INT);

-- -----------------------------------------------------
-- Placeholder table for view `tbl_geo_nation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_geo_nation` (`nation_id` INT, `nation` INT, `fnnumber` INT, `nation_engl` INT, `nation_deutsch` INT, `annotation` INT, `nation_code` INT, `usgs_code` INT, `iso_alpha_3_code` INT, `iso_alpha_2_code` INT, `region_id` INT, `language_variants` INT);

-- -----------------------------------------------------
-- Placeholder table for view `tbl_geo_province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_geo_province` (`province_id` INT, `provinz` INT, `provinz_local` INT, `provinz_code` INT, `nation_id` INT, `usgs_number` INT);

-- -----------------------------------------------------
-- Placeholder table for view `view_botanical_object_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view_botanical_object_search` (`id` INT, `derivative_id` INT, `scientific_name_id` INT, `genus` INT, `epithet` INT, `organisation_id` INT, `organisation_description` INT, `location` INT, `place_number` INT, `separated` INT, `index_seminum` INT, `greenhouse` INT, `accession_number` INT, `vegetative_count` INT, `type` INT);

-- -----------------------------------------------------
-- Placeholder table for view `view_classification_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view_classification_result` (`classification_id` INT, `scientific_name_id` INT, `acc_scientific_name_id` INT, `ref_date` INT, `preferred_taxonomy` INT, `annotations` INT, `locked` INT, `source` INT, `source_id` INT, `user_id` INT, `timestamp` INT, `parent_scientific_name_id` INT, `number` INT, `order` INT, `scientific_name` INT, `scientific_name_no_author` INT);

-- -----------------------------------------------------
-- procedure AddRevClassification
-- -----------------------------------------------------

USE `jacq_input`;
DROP procedure IF EXISTS `AddRevClassification`;

DELIMITER $$
USE `jacq_input`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddRevClassification`(
    IN `i_source` VARCHAR(15),
    IN `i_source_id` INT,
    OUT `o_uuid` VARCHAR(36)
)
BEGIN
	SET `o_uuid` = UUID();

	INSERT INTO `srvc_uuid_minter`(`uuid_minter_type_id`, `internal_id`, `uuid`) VALUES (3,`i_source_id`,`o_uuid`);
    
    SET @uuid_minter_id = LAST_INSERT_ID();

	-- insert classification entries
    INSERT INTO `rev_classification` (`uuid_minter_id`, `classification_id`, `scientific_name_id`, `acc_scientific_name_id`, `ref_date`, `preferred_taxonomy`, `annotations`, `locked`, `source`, `source_id`, `user_id`, `timestamp`, `parent_scientific_name_id`, `number`, `order`, `scientific_name`, `scientific_name_no_author`, `province_ids`, `province_codes`)
    SELECT @uuid_minter_id, tc.`classification_id`, tc.`scientific_name_id`, tc.`acc_scientific_name_id`, tc.`ref_date`, tc.`preferred_taxonomy`, tc.`annotations`, tc.`locked`, tc.`source`, tc.`source_id`, tc.`user_id`, tc.`timestamp`, tc.`parent_scientific_name_id`, tc.`number`, tc.`order`, GetScientificName(tc.`scientific_name_id`, 0, 0), GetScientificName(tc.`scientific_name_id`, 0, 1), tmp_cs.`province_ids`, tmp_cs.`province_codes`
	FROM `tbl_classification` tc
	LEFT JOIN
	(
		SELECT tccs.`scientific_name_id`, GROUP_CONCAT(tccs.`province_id` ORDER BY tgp.`provinz_code` ASC SEPARATOR ';') AS `province_ids`, GROUP_CONCAT(tgp.`provinz_code` ORDER BY tgp.`provinz_code` ASC SEPARATOR ';') AS `province_codes`
		FROM `tbl_classification_chorol_status` tccs
		LEFT JOIN `tbl_geo_province` tgp ON tccs.`province_id` = tgp.`province_id`
		GROUP BY `scientific_name_id`
	) AS `tmp_cs`
	ON tmp_cs.`scientific_name_id` = tc.`scientific_name_id`
	WHERE tc.`source` =  `i_source` AND tc.`source_id` = `i_source_id`;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function GetScientificName
-- -----------------------------------------------------

USE `jacq_input`;
DROP function IF EXISTS `GetScientificName`;

DELIMITER $$
USE `jacq_input`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `GetScientificName`(`p_taxonID` INT(11), `p_bAvoidHybridFormula` TINYINT(1) UNSIGNED, `p_bNoAuthor` TINYINT(1) UNSIGNED) RETURNS text CHARSET utf8
    READS SQL DATA
    COMMENT 'mirror function to herbar_view for simplicity'
BEGIN
  DECLARE v_scientificName TEXT;
  DECLARE v_author TEXT;
  
  CALL `herbar_view`._buildScientificNameComponents(p_taxonID, v_scientificName, v_author);
  
  IF p_bNoAuthor = 1 THEN
  	return v_scientificName;
  ELSE
  	return CONCAT_WS(' ', v_scientificName, v_author );
  END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetScientificNameComponents
-- -----------------------------------------------------

USE `jacq_input`;
DROP procedure IF EXISTS `GetScientificNameComponents`;

DELIMITER $$
USE `jacq_input`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetScientificNameComponents`(IN `p_taxonID` INT(11), OUT `p_genericEpithet` TEXT CHARSET utf8, OUT `p_specificEpithet` TEXT CHARSET utf8, OUT `p_infraspecificRank` TEXT CHARSET utf8, OUT `p_infraspecificEpithet` TEXT CHARSET utf8, OUT `p_author` TEXT CHARSET utf8)
    READS SQL DATA
BEGIN
  DECLARE v_genus varchar(100);
  DECLARE v_DallaTorreIDs int(11);
  DECLARE v_family varchar(100);
  DECLARE v_category varchar(2);
  DECLARE v_author_g varchar(255);
  DECLARE v_epithet varchar(100);
  DECLARE v_author varchar(100);
  DECLARE v_epithet1 varchar(100);
  DECLARE v_author1 varchar(100);
  DECLARE v_epithet2 varchar(100);
  DECLARE v_author2 varchar(100);
  DECLARE v_epithet3 varchar(100);
  DECLARE v_author3 varchar(100);
  DECLARE v_epithet4 varchar(100);
  DECLARE v_author4 varchar(100);
  DECLARE v_epithet5 varchar(100);
  DECLARE v_author5 varchar(100);
  DECLARE v_rank_abbr varchar(255);
  
  SELECT
    vt.`genus`, vt.`DallaTorreIDs`, vt.`family`, vt.`author_g`, vt.`epithet`, vt.`author`,
    vt.`epithet1`, vt.`author1`,vt.`epithet2`, vt.`author2`, vt.`epithet3`, vt.`author3`,
    vt.`epithet4`, vt.`author4`, vt.`epithet5`, vt.`author5`, vt.`rank_abbr`
  INTO
    v_genus, v_DallaTorreIDs, v_family, v_author_g, v_epithet, v_author, v_epithet1, v_author1,
    v_epithet2, v_author2, v_epithet3, v_author3, v_epithet4, v_author4, v_epithet5, v_author5,
    v_rank_abbr
  FROM
    `view_taxon` vt
  WHERE
    vt.`taxonID` = p_taxonID
  LIMIT 1;

  SET p_genericEpithet = v_genus;
  
  IF
    ( v_epithet IS NULL AND v_epithet1 IS NULL AND v_epithet2 IS NULL
    AND v_epithet3 IS NULL AND v_epithet4 IS NULL AND v_epithet5 IS NULL )
  THEN
    SET p_author = v_author_g;
  ELSE
    SET p_specificEpithet = v_epithet;
    SET p_infraspecificRank = v_rank_abbr;
    
    IF v_epithet IS NOT NULL THEN
      SET p_author = v_author;
    END IF;
    IF v_epithet1 IS NOT NULL THEN
      IF v_author1 IS NULL AND v_epithet1 = v_epithet THEN
        SET v_author1 = v_author;
      END IF;
      SET p_infraspecificEpithet = v_epithet1;
      SET p_author = v_author1;
    END IF;
    IF v_epithet2 IS NOT NULL THEN
      IF v_author2 IS NULL AND v_epithet2 = v_epithet THEN
        SET v_author2 = v_author;
      END IF;
      SET p_infraspecificEpithet = v_epithet2;
      SET p_author = v_author2;
    END IF;
    IF v_epithet3 IS NOT NULL THEN
      IF v_author3 IS NULL AND v_epithet3 = v_epithet THEN
        SET v_author3 = v_author;
      END IF;
      SET p_infraspecificEpithet = v_epithet3;
      SET p_author = v_author3;
    END IF;
    IF v_epithet4 IS NOT NULL THEN
      IF v_author4 IS NULL AND v_epithet4 = v_epithet THEN
        SET v_author4 = v_author;
      END IF;
      SET p_infraspecificEpithet = v_epithet4;
      SET p_author = v_author4;
    END IF;
    IF v_epithet5 IS NOT NULL THEN
      IF v_author5 IS NULL AND v_epithet5 = v_epithet THEN
        SET v_author5 = v_author;
      END IF;
      SET p_infraspecificEpithet = v_epithet5;
      SET p_author = v_author5;
    END IF;
  END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `view_taxon`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `view_taxon` ;
DROP TABLE IF EXISTS `view_taxon`;
USE `jacq_input`;
CREATE  OR REPLACE VIEW `view_taxon` AS
    select 
        `ts`.`taxonID` AS `taxonID`,
        `ts`.`synID` AS `synID`,
        `ts`.`basID` AS `basID`,
        `ts`.`genID` AS `genID`,
        `ts`.`annotation` AS `annotation`,
        `ts`.`external` AS `external`,
        `tg`.`genus` AS `genus`,
        `tg`.`DallaTorreIDs` AS `DallaTorreIDs`,
        `tg`.`DallaTorreZusatzIDs` AS `DallaTorreZusatzIDs`,
        `tag`.`author` AS `author_g`,
        `tf`.`family` AS `family`,
        `tsc`.`category` AS `category`,
        `tst`.`status` AS `status`,
        `tst`.`statusID` AS `statusID`,
        `tr`.`rank` AS `rank`,
        `tr`.`tax_rankID` AS `tax_rankID`,
        `tr`.`rank_abbr` AS `rank_abbr`,
        `ta`.`author` AS `author`,
        `ta`.`authorID` AS `authorID`,
        `ta`.`Brummit_Powell_full` AS `Brummit_Powell_full`,
        `ta1`.`author` AS `author1`,
        `ta1`.`authorID` AS `authorID1`,
        `ta1`.`Brummit_Powell_full` AS `bpf1`,
        `ta2`.`author` AS `author2`,
        `ta2`.`authorID` AS `authorID2`,
        `ta2`.`Brummit_Powell_full` AS `bpf2`,
        `ta3`.`author` AS `author3`,
        `ta3`.`authorID` AS `authorID3`,
        `ta3`.`Brummit_Powell_full` AS `bpf3`,
        `ta4`.`author` AS `author4`,
        `ta4`.`authorID` AS `authorID4`,
        `ta4`.`Brummit_Powell_full` AS `bpf4`,
        `ta5`.`author` AS `author5`,
        `ta5`.`authorID` AS `authorID5`,
        `ta5`.`Brummit_Powell_full` AS `bpf5`,
        `te`.`epithet` AS `epithet`,
        `te`.`epithetID` AS `epithetID`,
        `te1`.`epithet` AS `epithet1`,
        `te1`.`epithetID` AS `epithetID1`,
        `te2`.`epithet` AS `epithet2`,
        `te2`.`epithetID` AS `epithetID2`,
        `te3`.`epithet` AS `epithet3`,
        `te3`.`epithetID` AS `epithetID3`,
        `te4`.`epithet` AS `epithet4`,
        `te4`.`epithetID` AS `epithetID4`,
        `te5`.`epithet` AS `epithet5`,
        `te5`.`epithetID` AS `epithetID5`
    from
        ((((((((((((((((((`herbarinput`.`tbl_tax_species` `ts`
        left join `herbarinput`.`tbl_tax_authors` `ta` ON ((`ta`.`authorID` = `ts`.`authorID`)))
        left join `herbarinput`.`tbl_tax_authors` `ta1` ON ((`ta1`.`authorID` = `ts`.`subspecies_authorID`)))
        left join `herbarinput`.`tbl_tax_authors` `ta2` ON ((`ta2`.`authorID` = `ts`.`variety_authorID`)))
        left join `herbarinput`.`tbl_tax_authors` `ta3` ON ((`ta3`.`authorID` = `ts`.`subvariety_authorID`)))
        left join `herbarinput`.`tbl_tax_authors` `ta4` ON ((`ta4`.`authorID` = `ts`.`forma_authorID`)))
        left join `herbarinput`.`tbl_tax_authors` `ta5` ON ((`ta5`.`authorID` = `ts`.`subforma_authorID`)))
        left join `herbarinput`.`tbl_tax_epithets` `te` ON ((`te`.`epithetID` = `ts`.`speciesID`)))
        left join `herbarinput`.`tbl_tax_epithets` `te1` ON ((`te1`.`epithetID` = `ts`.`subspeciesID`)))
        left join `herbarinput`.`tbl_tax_epithets` `te2` ON ((`te2`.`epithetID` = `ts`.`varietyID`)))
        left join `herbarinput`.`tbl_tax_epithets` `te3` ON ((`te3`.`epithetID` = `ts`.`subvarietyID`)))
        left join `herbarinput`.`tbl_tax_epithets` `te4` ON ((`te4`.`epithetID` = `ts`.`formaID`)))
        left join `herbarinput`.`tbl_tax_epithets` `te5` ON ((`te5`.`epithetID` = `ts`.`subformaID`)))
        left join `herbarinput`.`tbl_tax_status` `tst` ON ((`tst`.`statusID` = `ts`.`statusID`)))
        left join `herbarinput`.`tbl_tax_rank` `tr` ON ((`tr`.`tax_rankID` = `ts`.`tax_rankID`)))
        left join `herbarinput`.`tbl_tax_genera` `tg` ON ((`tg`.`genID` = `ts`.`genID`)))
        left join `herbarinput`.`tbl_tax_authors` `tag` ON ((`tag`.`authorID` = `tg`.`authorID`)))
        left join `herbarinput`.`tbl_tax_families` `tf` ON ((`tf`.`familyID` = `tg`.`familyID`)))
        left join `herbarinput`.`tbl_tax_systematic_categories` `tsc` ON ((`tf`.`categoryID` = `tsc`.`categoryID`)));


-- -----------------------------------------------------
-- View `view_derivative_vegetative_count`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `view_derivative_vegetative_count` ;
DROP TABLE IF EXISTS `view_derivative_vegetative_count`;
USE `jacq_input`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`jacq`@`%` SQL SECURITY DEFINER VIEW `view_derivative_vegetative_count` AS select `vd`.`living_plant_id` AS `living_plant_id`,count(0) AS `vegetative_count` from `tbl_derivative_vegetative` `vd` group by `vd`.`living_plant_id`;

-- -----------------------------------------------------
-- View `view_person`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `view_person` ;
DROP TABLE IF EXISTS `view_person`;
USE `jacq_input`;
CREATE  OR REPLACE VIEW `view_person` AS
    SELECT 
        `tbl_person`.`id` AS `id`,
        `tbl_person`.`name` AS `name`
    FROM
        `tbl_person` 
    UNION SELECT 
        `herbarinput`.`tbl_collector`.`SammlerID` AS `SammlerID`,
        `herbarinput`.`tbl_collector`.`Sammler` AS `Sammler`
    FROM
        `herbarinput`.`tbl_collector`;

-- -----------------------------------------------------
-- View `view_scientificName`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `view_scientificName` ;
DROP TABLE IF EXISTS `view_scientificName`;
USE `jacq_input`;
CREATE  OR REPLACE VIEW `view_scientificName` AS
    SELECT 
        vt.taxonID AS scientific_name_id,
        GetScientificName(vt.taxonID, 0, 0) AS scientific_name,
        GetScientificName(vt.taxonID, 0, 1) AS scientific_name_no_author
    FROM
        `view_taxon` AS vt

;


-- -----------------------------------------------------
-- View `tbl_classification`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `tbl_classification` ;
DROP TABLE IF EXISTS `tbl_classification`;
USE `jacq_input`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tbl_classification` AS select `ts`.`tax_syn_ID` AS `classification_id`,`ts`.`taxonID` AS `scientific_name_id`,`ts`.`acc_taxon_ID` AS `acc_scientific_name_id`,`ts`.`ref_date` AS `ref_date`,`ts`.`preferred_taxonomy` AS `preferred_taxonomy`,`ts`.`annotations` AS `annotations`,`ts`.`locked` AS `locked`,ucase(replace(`ts`.`source`,'literature','citation')) AS `source`,coalesce(`ts`.`source_citationID`,`ts`.`source_person_ID`,`ts`.`source_serviceID`,`ts`.`source_specimenID`) AS `source_id`,`ts`.`userID` AS `user_id`,`ts`.`timestamp` AS `timestamp`,`tc`.`parent_taxonID` AS `parent_scientific_name_id`,`tc`.`number` AS `number`,`tc`.`order` AS `order` from (`herbarinput`.`tbl_tax_synonymy` `ts` left join `herbarinput`.`tbl_tax_classification` `tc` on((`ts`.`tax_syn_ID` = `tc`.`tax_syn_ID`)));

-- -----------------------------------------------------
-- View `tbl_classification_chorol_status`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `tbl_classification_chorol_status` ;
DROP TABLE IF EXISTS `tbl_classification_chorol_status`;
USE `jacq_input`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tbl_classification_chorol_status` AS select `herbarinput`.`tbl_tax_chorol_status`.`tax_chorol_status_ID` AS `classification_chorol_status_id`,`herbarinput`.`tbl_tax_chorol_status`.`taxonID_fk` AS `scientific_name_id`,(case when (`herbarinput`.`tbl_tax_chorol_status`.`citationID_fk` is not null) then 'CITATION' when (`herbarinput`.`tbl_tax_chorol_status`.`personID_fk` is not null) then 'PERSON' when (`herbarinput`.`tbl_tax_chorol_status`.`serviceID_fk` is not null) then 'SERVICE' end) AS `source`,coalesce(`herbarinput`.`tbl_tax_chorol_status`.`citationID_fk`,`herbarinput`.`tbl_tax_chorol_status`.`personID_fk`,`herbarinput`.`tbl_tax_chorol_status`.`serviceID_fk`) AS `source_id`,`herbarinput`.`tbl_tax_chorol_status`.`chorol_status` AS `chorol_status`,`herbarinput`.`tbl_tax_chorol_status`.`status_debatable` AS `status_debatable`,`herbarinput`.`tbl_tax_chorol_status`.`NationID_fk` AS `nation_id`,`herbarinput`.`tbl_tax_chorol_status`.`provinceID_fk` AS `province_id`,`herbarinput`.`tbl_tax_chorol_status`.`province_debatable` AS `province_debatable`,`herbarinput`.`tbl_tax_chorol_status`.`dateLastEdited` AS `date_last_edited`,`herbarinput`.`tbl_tax_chorol_status`.`locked` AS `locked` from `herbarinput`.`tbl_tax_chorol_status`;

-- -----------------------------------------------------
-- View `tbl_geo_nation`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `tbl_geo_nation` ;
DROP TABLE IF EXISTS `tbl_geo_nation`;
USE `jacq_input`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tbl_geo_nation` AS select `herbarinput`.`tbl_geo_nation`.`nationID` AS `nation_id`,`herbarinput`.`tbl_geo_nation`.`nation` AS `nation`,`herbarinput`.`tbl_geo_nation`.`fnnumber` AS `fnnumber`,`herbarinput`.`tbl_geo_nation`.`nation_engl` AS `nation_engl`,`herbarinput`.`tbl_geo_nation`.`nation_deutsch` AS `nation_deutsch`,`herbarinput`.`tbl_geo_nation`.`annotation` AS `annotation`,`herbarinput`.`tbl_geo_nation`.`nation_code` AS `nation_code`,`herbarinput`.`tbl_geo_nation`.`usgs_code` AS `usgs_code`,`herbarinput`.`tbl_geo_nation`.`iso_alpha_3_code` AS `iso_alpha_3_code`,`herbarinput`.`tbl_geo_nation`.`iso_alpha_2_code` AS `iso_alpha_2_code`,`herbarinput`.`tbl_geo_nation`.`regionID_fk` AS `region_id`,`herbarinput`.`tbl_geo_nation`.`language_variants` AS `language_variants` from `herbarinput`.`tbl_geo_nation`;

-- -----------------------------------------------------
-- View `tbl_geo_province`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `tbl_geo_province` ;
DROP TABLE IF EXISTS `tbl_geo_province`;
USE `jacq_input`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tbl_geo_province` AS select `herbarinput`.`tbl_geo_province`.`provinceID` AS `province_id`,`herbarinput`.`tbl_geo_province`.`provinz` AS `provinz`,`herbarinput`.`tbl_geo_province`.`provinz_local` AS `provinz_local`,`herbarinput`.`tbl_geo_province`.`provinz_code` AS `provinz_code`,`herbarinput`.`tbl_geo_province`.`nationID` AS `nation_id`,`herbarinput`.`tbl_geo_province`.`usgs_number` AS `usgs_number` from `herbarinput`.`tbl_geo_province`;

-- -----------------------------------------------------
-- View `view_botanical_object_search`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `view_botanical_object_search` ;
DROP TABLE IF EXISTS `view_botanical_object_search`;
USE `jacq_input`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`jacq`@`%` SQL SECURITY DEFINER VIEW `view_botanical_object_search` AS
select
          `bo`.`id`                             AS `id`
        ,`lp`.`id`                              AS `derivative_id`
        ,`bo`.`scientific_name_id`              AS `scientific_name_id`
        ,`vt`.`genus`                           AS `genus`
        ,`vt`.`epithet`                         AS `epithet`
        ,`bo`.`organisation_id`                 AS `organisation_id`
        ,`o`.`description`                      AS `organisation_description`
        ,`l`.`location`                         AS `location`
        ,`lp`.`place_number`                    AS `place_number`
        ,`bo`.`separated`                       AS `separated`
        ,`lp`.`index_seminum`                   AS `index_seminum`
        ,`o`.`greenhouse`                       AS `greenhouse`
        , LPAD(`lp`.`accession_number`, 7, '0') AS `accession_number`
        , ifnull(`dvc`.`vegetative_count`,0)    AS `vegetative_count`
        ,'living'                               AS `type`
from
          `tbl_living_plant` `lp`
          left join
                    `tbl_botanical_object` `bo`
                    on
                              `bo`.`id` = `lp`.`id`
          left join
                    `view_taxon` `vt`
                    on
                              `vt`.`taxonID` = `bo`.`scientific_name_id`
          left join
                    `tbl_organisation` `o`
                    on
                              `o`.`id` = `bo`.`organisation_id`
          left join
                    `tbl_acquisition_event` `ae`
                    on
                              `ae`.`id` = `bo`.`acquisition_event_id`
          left join
                    `tbl_location` `l`
                    on
                              `l`.`id` = `ae`.`location_id`
          left join
                    `view_derivative_vegetative_count` `dvc`
                    on
                              `dvc`.`living_plant_id` = `lp`.`id`

union

select
          `bo`.`id`                                                                      AS `id`
        ,`vd`.`derivative_vegetative_id`                                                 AS `derivative_id`
        ,`bo`.`scientific_name_id`                                                       AS `scientific_name_id`
        ,`vt`.`genus`                                                                    AS `genus`
        ,`vt`.`epithet`                                                                  AS `epithet`
        ,`vd`.`organisation_id`                                                          AS `organisation_id`
        ,`o`.`description`                                                               AS `organisation_description`
        ,`l`.`location`                                                                  AS `location`
        ,`vd`.`place_number`                                                             AS `place_number`
        ,`bo`.`separated`                                                                AS `separated`
        ,`vd`.`index_seminum`                                                            AS `index_seminum`
        ,`o`.`greenhouse`                                                                AS `greenhouse`
        , CONCAT_WS('-', LPAD(`lp`.`accession_number`, 7, '0'), `vd`.`accession_number`) AS `accession_number`
        , NULL                                                                           AS `vegetative_count`
        ,'vegetative'                                                                    AS `type`
from
          `tbl_derivative_vegetative` `vd`
          left join
                    `tbl_living_plant` `lp`
                    on
                              `lp`.`id` = `vd`.`living_plant_id`
          left join
                    `tbl_botanical_object` `bo`
                    on
                              `bo`.`id` = `lp`.`id`
          left join
                    `view_taxon` `vt`
                    on
                              `vt`.`taxonID` = `bo`.`scientific_name_id`
          left join
                    `tbl_organisation` `o`
                    on
                              `o`.`id` = `vd`.`organisation_id`
          left join
                    `tbl_acquisition_event` `ae`
                    on
                              `ae`.`id` = `bo`.`acquisition_event_id`
          left join
                    `tbl_location` `l`
                    on
                              `l`.`id` = `ae`.`location_id`;

-- -----------------------------------------------------
-- View `view_classification_result`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `view_classification_result` ;
DROP TABLE IF EXISTS `view_classification_result`;
USE `jacq_input`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_classification_result` AS select `c`.`classification_id` AS `classification_id`,`c`.`scientific_name_id` AS `scientific_name_id`,`c`.`acc_scientific_name_id` AS `acc_scientific_name_id`,`c`.`ref_date` AS `ref_date`,`c`.`preferred_taxonomy` AS `preferred_taxonomy`,`c`.`annotations` AS `annotations`,`c`.`locked` AS `locked`,`c`.`source` AS `source`,`c`.`source_id` AS `source_id`,`c`.`user_id` AS `user_id`,`c`.`timestamp` AS `timestamp`,`c`.`parent_scientific_name_id` AS `parent_scientific_name_id`,`c`.`number` AS `number`,`c`.`order` AS `order`,`sn`.`scientific_name` AS `scientific_name`,`sn`.`scientific_name_no_author` AS `scientific_name_no_author` from (`tbl_classification` `c` left join `view_scientificName` `sn` on((`c`.`scientific_name_id` = `sn`.`scientific_name_id`)));

-- -----------------------------------------------------
-- Data for table `frmwrk_user_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `frmwrk_user_type` (`user_type_id`, `type`) VALUES (1, 'gardener');
INSERT INTO `frmwrk_user_type` (`user_type_id`, `type`) VALUES (2, 'scientist');

COMMIT;


-- -----------------------------------------------------
-- Data for table `frmwrk_employment_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `frmwrk_employment_type` (`employment_type_id`, `type`) VALUES (1, 'fixed');
INSERT INTO `frmwrk_employment_type` (`employment_type_id`, `type`) VALUES (2, 'trainee');
INSERT INTO `frmwrk_employment_type` (`employment_type_id`, `type`) VALUES (3, 'seasonal');
INSERT INTO `frmwrk_employment_type` (`employment_type_id`, `type`) VALUES (4, 'left_company');
INSERT INTO `frmwrk_employment_type` (`employment_type_id`, `type`) VALUES (5, 'doctoral_candidate');
INSERT INTO `frmwrk_employment_type` (`employment_type_id`, `type`) VALUES (6, 'postdoc');
INSERT INTO `frmwrk_employment_type` (`employment_type_id`, `type`) VALUES (7, 'student');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_acquisition_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_acquisition_type` (`id`, `type`) VALUES (1, 'unknown');
INSERT INTO `tbl_acquisition_type` (`id`, `type`) VALUES (2, 'full extraction');
INSERT INTO `tbl_acquisition_type` (`id`, `type`) VALUES (3, 'partial extraction');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_phenology`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_phenology` (`id`, `phenology`) VALUES (1, 'unknown');
INSERT INTO `tbl_phenology` (`id`, `phenology`) VALUES (2, 'florid');
INSERT INTO `tbl_phenology` (`id`, `phenology`) VALUES (3, 'foliage');
INSERT INTO `tbl_phenology` (`id`, `phenology`) VALUES (4, 'fruit');
INSERT INTO `tbl_phenology` (`id`, `phenology`) VALUES (5, 'foliage_loss');
INSERT INTO `tbl_phenology` (`id`, `phenology`) VALUES (6, 'reduced');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_ident_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (1, 'aff.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (2, 'agg.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (3, 'cf.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (4, 'ined.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (5, 'masc.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (6, 's.l.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (7, 's.str.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (8, 'sp. nov.');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (9, 'x');
INSERT INTO `tbl_ident_status` (`ident_status_id`, `status`) VALUES (10, 'fem.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_index_seminum_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_index_seminum_type` (`id`, `type`) VALUES (1, 'WL');
INSERT INTO `tbl_index_seminum_type` (`id`, `type`) VALUES (2, 'KL');
INSERT INTO `tbl_index_seminum_type` (`id`, `type`) VALUES (3, 'WKL');
INSERT INTO `tbl_index_seminum_type` (`id`, `type`) VALUES (4, 'WS');
INSERT INTO `tbl_index_seminum_type` (`id`, `type`) VALUES (5, 'KS');
INSERT INTO `tbl_index_seminum_type` (`id`, `type`) VALUES (6, 'WKS');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_habitus_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_habitus_type` (`habitus_type_id`, `habitus`) VALUES (1, 'tree');
INSERT INTO `tbl_habitus_type` (`habitus_type_id`, `habitus`) VALUES (2, 'shrub');
INSERT INTO `tbl_habitus_type` (`habitus_type_id`, `habitus`) VALUES (3, 'herb');
INSERT INTO `tbl_habitus_type` (`habitus_type_id`, `habitus`) VALUES (4, 'Rhizomgeophyt');
INSERT INTO `tbl_habitus_type` (`habitus_type_id`, `habitus`) VALUES (5, 'Zwiebelgeophyt');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_sex`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_sex` (`id`, `sex`) VALUES (1, 'male');
INSERT INTO `tbl_sex` (`id`, `sex`) VALUES (2, 'female');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_separation_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (1, 'dead (spontaneous)');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (2, 'dead (eliminated)');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (3, 'dead (unknown cause)');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (4, 'harvested');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (5, 'separated');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (6, 'herbarium');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (7, 'unknown');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (8, 'pollen');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (9, 'DNA sample');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (10, 'seed');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (11, 'morphological fixation');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (12, 'cytological fixation');
INSERT INTO `tbl_separation_type` (`id`, `type`) VALUES (13, 'plant parts');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_relevancy_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_relevancy_type` (`id`, `type`, `important`) VALUES (1, 'sciences', 0);
INSERT INTO `tbl_relevancy_type` (`id`, `type`, `important`) VALUES (2, 'teachings', 0);
INSERT INTO `tbl_relevancy_type` (`id`, `type`, `important`) VALUES (3, 'protection', 0);
INSERT INTO `tbl_relevancy_type` (`id`, `type`, `important`) VALUES (4, 'public', 0);
INSERT INTO `tbl_relevancy_type` (`id`, `type`, `important`) VALUES (5, 'historic', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_sequence`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_sequence` (`id`) VALUES (0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_certificate_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_certificate_type` (`id`, `type`) VALUES (1, 'cites');
INSERT INTO `tbl_certificate_type` (`id`, `type`) VALUES (2, 'phyto');
INSERT INTO `tbl_certificate_type` (`id`, `type`) VALUES (3, 'pic');
INSERT INTO `tbl_certificate_type` (`id`, `type`) VALUES (4, 'abs');
INSERT INTO `tbl_certificate_type` (`id`, `type`) VALUES (5, 'zoll');
INSERT INTO `tbl_certificate_type` (`id`, `type`) VALUES (6, 'ipen');
INSERT INTO `tbl_certificate_type` (`id`, `type`) VALUES (7, 'custom');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_label_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_label_type` (`label_type_id`, `type`) VALUES (1, 'exhibition');
INSERT INTO `tbl_label_type` (`label_type_id`, `type`) VALUES (2, 'working');

COMMIT;


-- -----------------------------------------------------
-- Data for table `srvc_uuid_minter_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `srvc_uuid_minter_type` (`uuid_minter_type_id`, `description`, `timestamp`) VALUES (1, 'scientific_name', NOW());
INSERT INTO `srvc_uuid_minter_type` (`uuid_minter_type_id`, `description`, `timestamp`) VALUES (2, 'citation', NOW());
INSERT INTO `srvc_uuid_minter_type` (`uuid_minter_type_id`, `description`, `timestamp`) VALUES (3, 'classification', NOW());
INSERT INTO `srvc_uuid_minter_type` (`uuid_minter_type_id`, `description`, `timestamp`) VALUES (4, 'flora', NOW());

COMMIT;


-- -----------------------------------------------------
-- Data for table `tbl_inventory_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `tbl_inventory_type` (`inventory_type_id`, `type`, `timestamp`) VALUES (1, 'inventory', NOW());

COMMIT;


-- -----------------------------------------------------
-- Data for table `frmwrk_config`
-- -----------------------------------------------------
START TRANSACTION;
USE `jacq_input`;
INSERT INTO `frmwrk_config` (`fc_id`, `fc_name`, `fc_value`) VALUES (1, 'birt.work_label', '/opt/jacq-javaee/jacq-birt/hbv_worklabel.rptdesign');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
